from . import account_invoice
from . import delivery_rules
from . import models
from . import product
from . import product_producer
from . import purchase_order
from . import res_company
from . import res_config
from . import sale_order
from . import stock_location
from . import stock_picking
from . import website
from . import work_order
from . import mrp_workorder
from . import product_template
